# Generated by Django 6.0.4 on 2026-04-11 17:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('units', models.CharField(blank=True, default='', max_length=50)),
                ('minimum_stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_item', to='budget.budgetitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('add_stock', 'Add Stock'), ('remove_stock', 'Remove Stock')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='budget.budgetitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
