# Generated by Django 6.0.4 on 2026-04-11 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budgetitem_inventory_expense_inventory_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='expense',
        #     name='category',
        # ),
        migrations.AddField(
            model_name='budgetitem',
            name='category_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='budget_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='budget.budgetitem'),
        ),
    ]
